### ISSUE TITLE
Logos from Steam,Amazon,....

### ISSUE THREAD

**Issue by LilJay86** [Alan-oliveir/Playnite_E_Grid_View_Extend_Theme#2]
Hi, in your Screenshots are  Logos from Steam, Amazon, etc... 
Have I do something wrong that these Logos not shown when I use your Skin?

**Comment by Alan-oliveir** [comment]
Hi, these logos are provided by the Dublicate Hide extension: ![GitHub](https://github.com/felixkmh/DuplicateHider) 

My theme can be used without this extension. But it was made thinking about integrating with other extensions that you have installed.

Particularly I recommend using the extension DuplicateHider

**Comment by Alan-oliveir** [comment]
## Screenshots - Extension DuplicateHider
![Sem título_2](https://user-images.githubusercontent.com/105790117/227682406-78d19500-bf9a-4b2d-8840-448dbce63410.png)
![Sem título_1](https://user-images.githubusercontent.com/105790117/227682408-8716a692-9972-4063-be89-408e870edcaa.png)

**Comment by Alan-oliveir** [comment]
# DuplicateHider Configuration

![Sem título_4](https://user-images.githubusercontent.com/105790117/227682610-0fb864fb-7b35-4df1-adf8-ed506fe8c3dc.png)

If you have already installed the DuplicateHide extension, configure UI Integration with the same options as the image above to integrate the extension with the theme.

I hope I was able to help you. 

If you have any more problems with the extension you can comment.

**Comment by LilJay86** [comment]
Thx you for the Info. It Works!!! 👍 
Thx also for the great Skin 🥇
