### ISSUE TITLE
Background not shown in grid details view

### ISSUE THREAD

**Issue by scooterama** [Alan-oliveir/Playnite_E_Grid_View_Extend_Theme#3]
Doesn't show the wallpaper in Grid details. It's perfectly shown in details view.
[https://imgur.com/a/LsJ59GH](url)

**Comment by Alan-oliveir** [comment]
Could you send the images of both views again, please? I'm having trouble opening the link here.

**Comment by colorlime** [comment]
I'm experiencing the same issue. https://i.imgur.com/iFfqCML.jpeg

**Comment by Alan-oliveir** [comment]
I understand the error that is occurring. My theme was built to work alongside other extensions. In the specific case of this error, it seems to be a failure in the 'backgroundchanger' extension. Please check if this extension is installed and configured correctly.

**Comment by Alan-oliveir** [comment]
https://github.com/Lacro59/playnite-backgroundchanger-plugin

**Comment by Alan-oliveir** [comment]
Without this extension, it will be possible to use my theme with the background appearing in the Details View, but not in the Grid View. If you encounter any further difficulties, feel free to send a message.
